-- Made a new file because I AM NOT PUTTING ALL THIS in the main file 
-- Man why does animating stuff suck so much :( -NepDisk 

freeslot("SPR_HIT4","SPR_HIT5","SPR_HIT6","SPR_HIT7","SPR_HIT8","SPR_HIT9","SPR_HITX")

freeslot(
	"S_BATTLEPOINT4A",
	"S_BATTLEPOINT4B",
	"S_BATTLEPOINT4C",
	"S_BATTLEPOINT4D",
	"S_BATTLEPOINT4E",
	"S_BATTLEPOINT4F",
	"S_BATTLEPOINT4G",
	"S_BATTLEPOINT4H",
	"S_BATTLEPOINT4I",

	"S_BATTLEPOINT5A",
	"S_BATTLEPOINT5B",
	"S_BATTLEPOINT5C",
	"S_BATTLEPOINT5D",
	"S_BATTLEPOINT5E",
	"S_BATTLEPOINT5F",
	"S_BATTLEPOINT5G",
	"S_BATTLEPOINT5H",
	"S_BATTLEPOINT5I",

	"S_BATTLEPOINT6A",
	"S_BATTLEPOINT6B",
	"S_BATTLEPOINT6C",
	"S_BATTLEPOINT6D",
	"S_BATTLEPOINT6E",
	"S_BATTLEPOINT6F",
	"S_BATTLEPOINT6G",
	"S_BATTLEPOINT6H",
	"S_BATTLEPOINT6I",
	
	"S_BATTLEPOINT7A",
	"S_BATTLEPOINT7B",
	"S_BATTLEPOINT7C",
	"S_BATTLEPOINT7D",
	"S_BATTLEPOINT7E",
	"S_BATTLEPOINT7F",
	"S_BATTLEPOINT7G",
	"S_BATTLEPOINT7H",
	"S_BATTLEPOINT7I",
	
	"S_BATTLEPOINT8A",
	"S_BATTLEPOINT8B",
	"S_BATTLEPOINT8C",
	"S_BATTLEPOINT8D",
	"S_BATTLEPOINT8E",
	"S_BATTLEPOINT8F",
	"S_BATTLEPOINT8G",
	"S_BATTLEPOINT8H",
	"S_BATTLEPOINT8I",
	
	"S_BATTLEPOINT9A",
	"S_BATTLEPOINT9B",
	"S_BATTLEPOINT9C",
	"S_BATTLEPOINT9D",
	"S_BATTLEPOINT9E",
	"S_BATTLEPOINT9F",
	"S_BATTLEPOINT9G",
	"S_BATTLEPOINT9H",
	"S_BATTLEPOINT9I",
	
	"S_BATTLEPOINT10A",
	"S_BATTLEPOINT10B",
	"S_BATTLEPOINT10C",
	"S_BATTLEPOINT10D",
	"S_BATTLEPOINT10E",
	"S_BATTLEPOINT10F",
	"S_BATTLEPOINT10G",
	"S_BATTLEPOINT10H",
	"S_BATTLEPOINT10I"
)

states[S_BATTLEPOINT4A] =	{SPR_HIT4, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT4B}
states[S_BATTLEPOINT4B] =	{SPR_HIT4, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT4C}
states[S_BATTLEPOINT4C] =	{SPR_HIT4, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT4D}
states[S_BATTLEPOINT4D] =	{SPR_HIT4, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT4E}
states[S_BATTLEPOINT4E] =	{SPR_HIT4, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT4F}
states[S_BATTLEPOINT4F] =	{SPR_HIT4, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT4G}
states[S_BATTLEPOINT4G] =	{SPR_HIT4, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT4H}
states[S_BATTLEPOINT4H] =	{SPR_HIT4, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT4I}
states[S_BATTLEPOINT4I] =	{SPR_HIT4, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}

states[S_BATTLEPOINT5A] =	{SPR_HIT5, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT5B}
states[S_BATTLEPOINT5B] =	{SPR_HIT5, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT5C}
states[S_BATTLEPOINT5C] =	{SPR_HIT5, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT5D}
states[S_BATTLEPOINT5D] =	{SPR_HIT5, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT5E}
states[S_BATTLEPOINT5E] =	{SPR_HIT5, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT5F}
states[S_BATTLEPOINT5F] =	{SPR_HIT5, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT5G}
states[S_BATTLEPOINT5G] =	{SPR_HIT5, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT5H}
states[S_BATTLEPOINT5H] =	{SPR_HIT5, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT5I}
states[S_BATTLEPOINT5I] =	{SPR_HIT5, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}

states[S_BATTLEPOINT6A] =	{SPR_HIT6, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT6B}
states[S_BATTLEPOINT6B] =	{SPR_HIT6, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT6C}
states[S_BATTLEPOINT6C] =	{SPR_HIT6, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT6D}
states[S_BATTLEPOINT6D] =	{SPR_HIT6, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT6E}
states[S_BATTLEPOINT6E] =	{SPR_HIT6, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT6F}
states[S_BATTLEPOINT6F] =	{SPR_HIT6, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT6G}
states[S_BATTLEPOINT6G] =	{SPR_HIT6, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT6H}
states[S_BATTLEPOINT6H] =	{SPR_HIT6, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT6I}
states[S_BATTLEPOINT6I] =	{SPR_HIT6, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}

states[S_BATTLEPOINT7A] =	{SPR_HIT7, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT7B}
states[S_BATTLEPOINT7B] =	{SPR_HIT7, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT7C}
states[S_BATTLEPOINT7C] =	{SPR_HIT7, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT7D}
states[S_BATTLEPOINT7D] =	{SPR_HIT7, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT7E}
states[S_BATTLEPOINT7E] =	{SPR_HIT7, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT7F}
states[S_BATTLEPOINT7F] =	{SPR_HIT7, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT7G}
states[S_BATTLEPOINT7G] =	{SPR_HIT7, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT7H}
states[S_BATTLEPOINT7H] =	{SPR_HIT7, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT7I}
states[S_BATTLEPOINT7I] =	{SPR_HIT7, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}

states[S_BATTLEPOINT8A] =	{SPR_HIT8, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT8B}
states[S_BATTLEPOINT8B] =	{SPR_HIT8, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT8C}
states[S_BATTLEPOINT8C] =	{SPR_HIT8, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT8D}
states[S_BATTLEPOINT8D] =	{SPR_HIT8, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT8E}
states[S_BATTLEPOINT8E] =	{SPR_HIT8, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT8F}
states[S_BATTLEPOINT8F] =	{SPR_HIT8, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT8G}
states[S_BATTLEPOINT8G] =	{SPR_HIT8, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT8H}
states[S_BATTLEPOINT8H] =	{SPR_HIT8, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT8I}
states[S_BATTLEPOINT8I] =	{SPR_HIT8, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}

states[S_BATTLEPOINT9A] =	{SPR_HIT9, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT9B}
states[S_BATTLEPOINT9B] =	{SPR_HIT9, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT9C}
states[S_BATTLEPOINT9C] =	{SPR_HIT9, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT9D}
states[S_BATTLEPOINT9D] =	{SPR_HIT9, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT9E}
states[S_BATTLEPOINT9E] =	{SPR_HIT9, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT9F}
states[S_BATTLEPOINT9F] =	{SPR_HIT9, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT9G}
states[S_BATTLEPOINT9G] =	{SPR_HIT9, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT9H}
states[S_BATTLEPOINT9H] =	{SPR_HIT9, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT9I}
states[S_BATTLEPOINT9I] =	{SPR_HIT9, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}

states[S_BATTLEPOINT10A] =	{SPR_HITX, FF_FULLBRIGHT, 7, nil, 0, 0, S_BATTLEPOINT10B}
states[S_BATTLEPOINT10B] =	{SPR_HITX, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT10C}
states[S_BATTLEPOINT10C] =	{SPR_HITX, FF_FULLBRIGHT|4, 1, nil, 0, 0, S_BATTLEPOINT10D}
states[S_BATTLEPOINT10D] =	{SPR_HITX, FF_FULLBRIGHT|3, 1, nil, 0, 0, S_BATTLEPOINT10E}
states[S_BATTLEPOINT10E] =	{SPR_HITX, FF_FULLBRIGHT|2, 1, nil, 0, 0, S_BATTLEPOINT10F}
states[S_BATTLEPOINT10F] =	{SPR_HITX, FF_FULLBRIGHT|1, 1, nil, 0, 0, S_BATTLEPOINT10G}
states[S_BATTLEPOINT10G] =	{SPR_HITX, FF_FULLBRIGHT|2, TICRATE, nil, 0, 0, S_BATTLEPOINT10H}
states[S_BATTLEPOINT10H] =	{SPR_HITX, FF_FULLBRIGHT|5, 1, nil, 0, 0, S_BATTLEPOINT10I}
states[S_BATTLEPOINT10I] =	{SPR_HITX, FF_FULLBRIGHT|6, 1, nil, 0, 0, S_NULL}